version: "3"
services:
    db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
          SA_PASSWORD: "Password@12345"
          ACCEPT_EULA: "Y"
      ports:
        - "14331:1433" 

    inventory:
        build: 
            context: ./src
            dockerfile: Dockerfile
        ports: 
          - "5001:80"
        depends_on: 
          - db
          - zookeeper
          - kafka
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"

    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

    kafka:
      container_name: kafka_broker_1
      image: wurstmeister/kafka
      links:
        - zookeeper
      ports:
        - "9092:9092"
        - "29092:29092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOSTNAME: kafka
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

