name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  Inventory_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: uj-master-thesis/Uploader
        path: Uploader
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Inventory.sln
    - name: Build
      run: dotnet build ./src/Inventory.sln --no-restore
    - name: Test
      run: dotnet test ./src/Inventory.sln --no-build --verbosity normal
